//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: AssemblyInformationalVersion("8.2.524")]
[assembly: AssemblyCompany("Carrier Corporation")]
[assembly: AssemblyCopyright("Carrier")]
[assembly: AssemblyFileVersion("8.2.524.126")]
[assembly: AssemblyVersion("8.2.524.126")]


